[toolchain]
anchor_version = "0.29.0"

[features]
resolution = true
skip-lint = false

[programs.devnet]
rebalancing = "2RNkDWBs3fCeA6r6aAA9fBfAx6A4fgQ8V24mutQkZyEt"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "wallet/wallet.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
